version: '3.0'
services:
  gcloud:
    image: google/cloud-sdk:alpine
    platform: linux/x86_64
    volumes:
      - ./src:/src
      - gcloud_data:/root/.config/gcloud
    working_dir: /src
    entrypoint: bash
    tty: true

volumes:
  gcloud_data: